version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship
      - name: product
        identifier: raw_gz_product